apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: foobar
      image: omisha/image_foo:bar
      imagePullPolicy: Always
      command: [ echo, SUCCESS ]
  imagePullSecrets:
    - name: regcred

