apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: foobar
      image: omisha/foo:bar
      imagePullPolicy: Always
      command: [ "echo", "SUCCESS" ]
  imagePullSecrets:
    - name: omisha
